-- Add sixth batch of internships covering remaining Massachusetts cities
insert into public.internships (name, city, type, category, featured) values
  ('Malden Catholic High School Education Intern',  'Malden',       'in-person', 'Education',        false),
  ('Malden Community Health Center Intern',         'Malden',       'in-person', 'Biology',          false),
  ('Everett Public Schools STEM Intern',            'Everett',      'in-person', 'Education',        false),
  ('Encore Boston Harbor Hospitality Intern',       'Everett',      'in-person', 'Business',         false),
  ('Beverly Hospital Clinical Research Intern',     'Beverly',      'in-person', 'Biology',          false),
  ('Endicott College Marketing Co-op',              'Beverly',      'in-person', 'Marketing',        false),
  ('Andover Public Schools Teaching Fellow',        'Andover',      'in-person', 'Education',        false),
  ('Raytheon Technologies Engineering Intern',      'Andover',      'in-person', 'Engineering',      false),
  ('Taunton Regional Medical Center Intern',        'Taunton',      'in-person', 'Biology',          false),
  ('Attleboro Arts Museum Creative Intern',         'Attleboro',    'in-person', 'Arts',             false),
  ('Smith College Research Lab Intern',             'Northampton',  'in-person', 'Biology',          false),
  ('Northampton Arts Council Program Intern',       'Northampton',  'in-person', 'Arts',             false),
  ('UMass Amherst CS Research Fellow',              'Amherst',      'in-person', 'Computer Science', true),
  ('UMass Amherst Biology Lab Assistant',           'Amherst',      'in-person', 'Biology',          false),
  ('Holyoke Medical Center Nursing Extern',         'Holyoke',      'in-person', 'Biology',          false),
  ('Holyoke Community College IT Intern',           'Holyoke',      'in-person', 'Computer Science', false),
  ('Plymouth Plantation Museum Arts Intern',        'Plymouth',     'in-person', 'Arts',             false),
  ('Jordan Hospital Research Intern',               'Plymouth',     'in-person', 'Biology',          false),
  ('Fitchburg Art Museum Creative Intern',          'Fitchburg',    'in-person', 'Arts',             false),
  ('Leominster Public Schools Education Intern',    'Leominster',   'in-person', 'Education',        false),
  ('Remote Cybersecurity Analyst Intern',           'Andover',      'virtual',   'Computer Science', false),
  ('Virtual Environmental Law Clinic Intern',       'Northampton',  'virtual',   'Law',              false),
  ('Remote Content Marketing Strategist Intern',    'Beverly',      'virtual',   'Marketing',        false),
  ('Online Biology Tutoring Program Intern',        'Amherst',      'virtual',   'Education',        false);
