-- Add fourth batch of internship listings expanding into new MA cities and categories
insert into public.internships (name, city, type, category, featured) values
  ('Beth Israel Deaconess Medical Intern',         'Boston',       'in-person', 'Biology',          false),
  ('Liberty Mutual Insurance Tech Intern',         'Boston',       'in-person', 'Computer Science', false),
  ('Boston Symphony Orchestra Arts Intern',        'Boston',       'in-person', 'Arts',             false),
  ('Wellington Management Finance Intern',         'Boston',       'virtual',   'Business',         false),
  ('Northeastern Co-op AI Research Fellow',        'Boston',       'in-person', 'Computer Science', true),
  ('CIC Cambridge Startup Operations Intern',      'Cambridge',    'in-person', 'Business',         false),
  ('MIT Lincoln Laboratory Engineering Intern',    'Cambridge',    'in-person', 'Engineering',      false),
  ('Whitehead Institute Biology Research Intern',  'Cambridge',    'in-person', 'Biology',          false),
  ('Medford Public Schools Teaching Intern',       'Medford',      'in-person', 'Education',        false),
  ('Tufts University Lab Research Aide',           'Medford',      'in-person', 'Biology',          false),
  ('Quincy Medical Group Clinical Intern',         'Quincy',       'in-person', 'Biology',          false),
  ('Quincy City Hall Policy Intern',               'Quincy',       'in-person', 'Law',              false),
  ('New Bedford Whaling Museum Arts Intern',       'New Bedford',  'in-person', 'Arts',             false),
  ('UMass Dartmouth Engineering Co-op',            'New Bedford',  'in-person', 'Engineering',      false),
  ('Pittsfield Community Theater Arts Intern',     'Pittsfield',   'in-person', 'Arts',             false),
  ('Berkshire Medical Center Research Intern',     'Pittsfield',   'in-person', 'Biology',          false),
  ('Lynn Public Schools Education Intern',         'Lynn',         'in-person', 'Education',        false),
  ('GE Vernova Grid Engineering Intern',           'Lynn',         'in-person', 'Engineering',      false),
  ('Remote Biotech Data Analysis Intern',          'Boston',       'virtual',   'Biology',          false),
  ('Virtual Civil Rights Law Clinic Intern',       'Springfield',  'virtual',   'Law',              false),
  ('Remote Education Policy Research Intern',      'Cambridge',    'virtual',   'Education',        false),
  ('Online Game Development Intern',               'Boston',       'virtual',   'Computer Science', false);
