-- Add fifth batch of internships expanding into more Massachusetts cities
insert into public.internships (name, city, type, category, featured) values
  ('Salem Hospital Nursing Extern',                'Salem',        'in-person', 'Biology',          false),
  ('Peabody Essex Museum Arts Intern',             'Salem',        'in-person', 'Arts',             false),
  ('Analog Devices Hardware Engineering Intern',   'Wilmington',   'in-person', 'Engineering',      false),
  ('Haverhill Public Library Education Intern',    'Haverhill',    'in-person', 'Education',        false),
  ('Lawrence Community Works Nonprofit Intern',    'Lawrence',     'in-person', 'Education',        false),
  ('Merrimack Valley Food Bank Intern',            'Lawrence',     'in-person', 'Education',        false),
  ('Newton-Wellesley Hospital Research Intern',    'Newton',       'in-person', 'Biology',          false),
  ('Newton Public Schools Teaching Fellow',        'Newton',       'in-person', 'Education',        false),
  ('Framingham State University Lab Intern',       'Framingham',   'in-person', 'Biology',          false),
  ('Staples Inc. IT Operations Intern',            'Framingham',   'in-person', 'Computer Science', false),
  ('Waltham Labs Biotech Research Intern',         'Waltham',      'in-person', 'Biology',          false),
  ('Brandeis University CS Research Aide',         'Waltham',      'in-person', 'Computer Science', false),
  ('Brockton Community Health Center Intern',      'Brockton',     'in-person', 'Biology',          false),
  ('Brockton Area Transit Marketing Intern',       'Brockton',     'in-person', 'Marketing',        false),
  ('UMass Fall River Engineering Co-op',           'Fall River',   'in-person', 'Engineering',      false),
  ('SouthCoast Health Clinical Intern',            'Fall River',   'in-person', 'Biology',          false),
  ('Gloucester Maritime Heritage Arts Intern',     'Gloucester',   'in-person', 'Arts',             false),
  ('Addison Gilbert Hospital Research Intern',     'Gloucester',   'in-person', 'Biology',          false),
  ('Remote Full-Stack Engineering Fellowship',     'Waltham',      'virtual',   'Computer Science', false),
  ('Virtual Public Health Policy Intern',          'Newton',       'virtual',   'Law',              false),
  ('Remote Social Media Marketing Intern',         'Salem',        'virtual',   'Marketing',        false),
  ('Online K-12 Curriculum Design Intern',         'Lawrence',     'virtual',   'Education',        false);
